
let D={},current=null,index=0,left=0,total=0,tick=null,paused=false;const app=document.getElementById('app');
fetch('trainings.json').then(r=>r.json()).then(d=>{D=d;world()});
function shell(body,back=''){app.innerHTML=`<div class="wrap"><div class="top"><div class="brand"><b>10'</b> MINUTEN ON TOP</div>${back?`<button class="back" onclick="${back}">← ZURÜCK</button>`:''}</div>${body}</div><section id="timer" class="timer"></section>`}
function world(){clearInterval(tick);shell(`<section class="hero"><small>DEINE TRAININGSWELT</small><h1>WÄHLE DEIN TRAINING.</h1><p>Neun vorbereitete Trainings. Drei Welten. Rund zehn Minuten.</p></section><section class="world"><img src="assets/welt.jpg" alt="Trainingswelt">${Object.keys(D).map(k=>`<button class="marker m${k}" onclick="openSet('${k}')"><i>${k}</i><span>${D[k].title}<small>${D[k].claim}</small></span></button>`).join('')}</section>`)}
function openSet(k){current=k;let s=D[k];shell(`<section class="visual"><img src="assets/training-${k}.jpg"><div class="veil"></div><div class="training-title"><small>${s.zone} · TRAINING ${k}</small><h1>${s.title}</h1><p>${s.claim}</p><div class="meta"><span>4 Übungen</span><span>${s.rounds} Runden</span><span>${s.pause} Sek. Pause</span></div></div></section><section class="grid">${s.ex.map((e,i)=>`<button class="card" onclick="start(${i})"><span class="step">${i+1}</span><h2>${e[0]}</h2><div class="time">${e[1]} SEK.</div><div class="cue"><b>1.</b> ${e[2]}<br><b>2.</b> ${e[3]}</div><div class="go">TIMER STARTEN →</div></button>`).join('')}</section><section class="anchor"><b>ANKER</b> · Nach der letzten Runde ${s.breath||45} Sekunden ruhig atmen.</section>`,'world()')}
function start(i){index=i;total=D[current].ex[i][1];left=total;paused=false;clearInterval(tick);render();document.getElementById('timer').classList.add('on');tick=setInterval(()=>{if(!paused){left--;render();if(left<=0)clearInterval(tick)}},1000)}
function render(){let e=D[current].ex[index];document.getElementById('timer').innerHTML=`<article class="panel"><small>${D[current].title} · ${index+1}/4</small><h2>${e[0]}</h2><p><b>${e[2]}</b><br>${e[3]}</p><div class="clock">${String(Math.max(0,left)).padStart(2,'0')}</div><div class="controls"><button onclick="move(-1)">← VORHERIGE</button><button class="main" onclick="toggle()">${paused?'WEITER':'PAUSE'}</button><button onclick="move(1)">NÄCHSTE →</button></div><button class="close" onclick="closeTimer()">ZUR ÜBERSICHT</button></article>`}
function toggle(){paused=!paused;render()}function move(d){start(Math.max(0,Math.min(3,index+d)))}function closeTimer(){clearInterval(tick);document.getElementById('timer').classList.remove('on')}
