
let t=null,run=null;const app=document.getElementById('app');
fetch('training.json').then(r=>r.json()).then(d=>{t=d;renderTraining()}).catch(()=>app.innerHTML='<p style="padding:30px">Training konnte nicht geladen werden.</p>');
const head=()=>`<header class="topbar"><div class="brand"><span class="brand-badge">10′</span><span>MINUTEN ON TOP</span></div><button class="back" onclick="renderWorld()">← ZURÜCK ZUR WELT</button></header>`;
function renderTraining(){clearRun();app.innerHTML=`<div class="shell">${head()}<section class="hero"><div><h1>${t.title}</h1><p>${t.statement}</p></div><div class="helper"><b>SO TRAINIERST DU</b><br>Wähle eine Übung. Schau zuerst die Bewegung an. Starte dann den Timer.</div></section><section class="grid">${t.exercises.map((e,i)=>card(e,i)).join('')}</section></div>`}
function card(e,i){return `<article class="card" id="card-${e.id}"><div class="card-head"><span class="num">${i+1}</span><h2>${e.title}</h2></div><div class="visual"><img src="${e.image}" alt="${e.title}"></div><div class="card-body"><ul class="steps">${e.steps.map(s=>`<li>${s}</li>`).join('')}</ul><div class="controls"><div class="duration">◷ ${e.duration} SEKUNDEN</div><button class="start" onclick="start('${e.id}')">START</button></div><div class="timerbox"><div class="clock" data-clock="${e.id}">00:${String(e.duration).padStart(2,'0')}</div><div class="track"><div class="fill" data-fill="${e.id}"></div></div><div class="timer-actions"><button class="pause" onclick="pause()">PAUSE</button><button class="again" onclick="restart('${e.id}')">NOCHMALS</button><button class="close" onclick="stop()">SCHLIESSEN</button></div></div></div></article>`}
function renderWorld(){clearRun();app.innerHTML=`<section class="world"><div class="world-wrap"><img src="world.jpg" alt="Trainingswelt"><button class="world-hot" onclick="renderTraining()" aria-label="Fels öffnen"></button></div></section>`}
function start(id){clearRun();document.querySelectorAll('.card').forEach(c=>c.classList.remove('active'));let e=t.exercises.find(x=>x.id===id);document.getElementById('card-'+id).classList.add('active');runTimer(e)}
function runTimer(e){let left=e.duration;update(e.id,left,e.duration);run={id:e.id,left,total:e.duration,paused:false,interval:setInterval(()=>{if(!run||run.paused)return;run.left--;update(e.id,run.left,run.total);if(run.left<=0){beep();clearInterval(run.interval);run.interval=null}},1000)}}
function update(id,left,total){let c=document.querySelector(`[data-clock="${id}"]`),f=document.querySelector(`[data-fill="${id}"]`);if(c)c.textContent='00:'+String(Math.max(0,left)).padStart(2,'0');if(f)f.style.transform=`scaleX(${Math.max(0,left/total)})`}
function pause(){if(run)run.paused=!run.paused}
function restart(id){let e=t.exercises.find(x=>x.id===id);clearRun();document.getElementById('card-'+id).classList.add('active');runTimer(e)}
function stop(){clearRun();document.querySelectorAll('.card').forEach(c=>c.classList.remove('active'))}
function clearRun(){if(run?.interval)clearInterval(run.interval);run=null}
function beep(){try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=700;g.gain.value=.08;o.start();o.stop(a.currentTime+.18)}catch(e){}}
